jtalks-org/jcommune

- jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/topic/topicForm.jsp
Added validation of branch on NULL
> JC-1669 Wrong page title when validation error happens during topic creation

- jcommune-view/jcommune-web-view/src/main/webapp/resources/css/app/application.css
Here is explanation of problem:
http://stackoverflow.com/questions/12501224/
twitter-bootstrap-buttons-hover-style
Fixed by increasing background-position css style param
> JC-2130 Problem of crossing over buttons by white line is fixed

- jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/banner.js
Now input text has default focus in banner uploading dialog.
> JC-1547 No default focus in the banner uploading dialog.

- docs/installation/jcommune.xml
Add doc on how to change logger config location in jcommune.xml
> JC-1169 Configuring place to log

- jcommune-plugin-api/src/main/java/org/jtalks/jcommune/plugin/api/web/dto/PostDto.java
- jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/topic/postList.jsp
- jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/postDraft.js
Fix for Saving Drafts history issue with countdown while saving drafts.
> JC-1739 Countdown while saving drafts fix

- jcommune-model/src/main/resources/org/jtalks/jcommune/model/sample-forum.sql
Added 'ignore' in insertion into acl_object_identity to prevent
re-creared groups that were created via poulpe.
Added new variables for insertion personal permissions in acl_entry. If
groups created only via script new variables is equals to old ones (
@..._group_object_identity), but it prevents from link to unexisting id
when groups were created via poulpe.
> Modify sql-script JC-2145

- jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V69__Remove_Column_State_From_Post_Table.sql
Pull request for issue [JC-2244](http://jira.jtalks.org/browse/JC-2244)
> JC-2244 Remove column STATE from POST table

- jcommune-plugin-api/src/main/java/org/jtalks/jcommune/plugin/api/PluginClassLoader.java
- jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/template/decorator.jsp
- jcommune-view/jcommune-web-view/src/main/webapp/resources/css/app/application.css
- jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/registration.js
- change captcha image style
- handle enter key for jsp registration form
- union captcha-image style for both stand alone and modal registration windows
- fix debug log in PluginClassLoader
- remove double include of registraion.js
> JC-2086 refresh captcha in registration page by pressing Enter key.

- jcommune-plugins/questions-n-answers-plugin/src/main/resources/org/jtalks/jcommune/plugin/questionsandanswers/template/question.vm
- added check for anonymous user when inserting the tooltip for
vote buttons.
> JC-2250 Error messages are not shown for anonymous user when he tries to vote up/down

- jcommune-model/src/main/java/org/jtalks/jcommune/model/validation/annotations/AtLeastOneFieldIsNotNull.java
- jcommune-model/src/main/java/org/jtalks/jcommune/model/validation/annotations/TopicDraftNumberOfPollItems.java
- jcommune-model/src/main/java/org/jtalks/jcommune/model/validation/validators/AtLeastOneFieldIsNotNullValidator.java
- jcommune-model/src/main/java/org/jtalks/jcommune/model/validation/validators/TopicDraftNumberOfPollItemsValidator.java
- jcommune-model/src/test/java/org/jtalks/jcommune/model/entity/TopicDraftTest.java
- jcommune-model/src/test/java/org/jtalks/jcommune/model/validation/AtLeastOneFieldIsNotNullValidatorTest.java
- jcommune-model/src/test/java/org/jtalks/jcommune/model/validation/TopicDraftNumberOfPollItemsValidatorTest.java
- jcommune-plugin-api/src/main/java/org/jtalks/jcommune/plugin/api/service/PluginTopicDraftService.java
- jcommune-plugin-api/src/main/java/org/jtalks/jcommune/plugin/api/service/transactional/TransactionalPluginTopicDraftService.java
- add missed copyright headers
> JC-2201 Save Drafts on writing topics

- jcommune-service/src/main/resources/kefirbb.xml
> JC-2210 Dummy image is not loaded in firefox,

- jcommune-plugin-api/src/main/java/org/jtalks/jcommune/plugin/api/web/dto/json/JsonResponse.java
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/UserControllerTest.groovy
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/service/GroupsManager.java
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/service/GroupsService.java
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/JsonResponseUtils.java
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Users.groovy
JC-2292 review changes:
- mockMvc deleted from tests
- some tests renamed
- code convention fixes
JC-2292 review fixes
> JC-2292 Groups manage spock tests

- docs/installation/general-installation-guide.md
- docs/installation/linux/basic-environment.md
- docs/installation/windows/basic-environment.md
- How to enable UTF8MB4 character set by default.
> MySQL config guide

- jcommune-performance-tests/pom.xml
- jcommune-performance-tests/src/test/resources/gatling.conf
- jcommune-performance-tests/src/test/resources/logback.xml
- jcommune-performance-tests/src/test/resources/recorder.conf
- jcommune-performance-tests/src/test/scala/Engine.scala
- jcommune-performance-tests/src/test/scala/IDEPathHelper.scala
- jcommune-performance-tests/src/test/scala/Recorder.scala
- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenForumMainPage.scala
- All tests can be placed in the package org.jtalks.jcommune.performance.tests
> Add Performance tests

- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/Login.scala
- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenBranchPage.scala
- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenForumMainPage.scala
- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenRecentActivityPage.scala
- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenTopicPage.scala
Added proper headers to scala tests
> Fixed license headers

- jcommune-service/src/main/java/org/jtalks/jcommune/service/security/AclGroupPermissionEvaluator.java
- jcommune-service/src/main/resources/org/jtalks/jcommune/service/security-service-context.xml
- jcommune-service/src/test/java/org/jtalks/jcommune/service/security/AclGroupPermissionEvaluatorTest.java
- pom.xml
- updated jtalks-common version to 0.62
- decreased number of sql queries generated in hasPermission() method.
> JC-2360 Speed Up Forum

- jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/utils/ScnBuilder.scala
- reduced the number of user requests for (openBranch and openTopic)
> gatling tests optimization

- jcommune-model/src/main/java/org/jtalks/jcommune/model/entity/JCUser.java
- jcommune-service/src/main/java/org/jtalks/jcommune/service/transactional/TransactionalUserService.java
- jcommune-service/src/main/resources/org/jtalks/jcommune/service/applicationContext-service.xml
- jcommune-service/src/test/java/org/jtalks/jcommune/service/transactional/TransactionalUserServiceTest.java
- Everytime when we need to get the current user, we searched it by name (case insensitive way). So indexes wasn't worked and we searched through all users. Now current user is taken from session.
> JC-2380 SpeedUpForum

- jcommune-service/src/main/java/org/jtalks/jcommune/service/bb2htmlprocessors/UrlToLinkConvertPostProcessor.java
- jcommune-service/src/test/java/org/jtalks/jcommune/service/bb2htmlprocessors/UrlToLinkConvertPostProcessorTest.java
- Cyrillic domain name support
- Some additional test cases
- typo fixes
> JC-1178 Cyrillic domain name support

- jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/groupAdministration.jsp
-fixed XSS vulnerability through group description field
> JC-2367 Edit user groups

- jcommune-model/src/main/java/org/jtalks/jcommune/model/entity/JCommuneProperty.java
- jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V74__Add_Email_Black_List_Property.sql
- jcommune-model/src/main/resources/org/jtalks/jcommune/model/entity/applicationContext-properties.xml
- jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/controller/UserController.java
- jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/UserControllerTest.java
- Added ability to block new user registration, if email address in the black list
> JC-2389 Email black-list

- jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/forumAdministration.js
- colour of delete button in 'delete group' dialog changed to default (blue)
> JC-2369 Delete user groups

- jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/groupUserList.jsp
- jcommune-view/jcommune-web-view/src/main/webapp/resources/css/app/application.css
- jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/forumAdministration.js
- added button "add user to group" (isn't visible by default, to see button in
'group users administration page' you should add URL request param
'display-button=on')
> JC-2400 Add user to group

- jcommune-model/src/main/java/org/jtalks/jcommune/model/dao/UserDao.java
- jcommune-model/src/main/java/org/jtalks/jcommune/model/dao/hibernate/UserHibernateDao.java
- jcommune-model/src/main/java/org/jtalks/jcommune/model/dto/UserDto.java
- jcommune-model/src/main/resources/org/jtalks/jcommune/model/entity/JCUser.hbm.xml
- jcommune-model/src/test/java/org/jtalks/jcommune/model/dao/hibernate/UserHibernateDaoTest.java
- jcommune-service/src/main/java/org/jtalks/jcommune/service/UserService.java
- jcommune-service/src/main/java/org/jtalks/jcommune/service/transactional/TransactionalUserService.java
- jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/controller/AdministrationController.java
- jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/AdministrationControllerTest.java
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/AdministrationControllerTest.groovy
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Groups.groovy
- jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Users.groovy
with name and email matching pattern
> JC-2400 Service to get user out of appropriate group
