jtalks-org/jcommune

jcommune-view/jcommune-web-view/src/main/webapp/resources/css/app/application.css
Edited CSS classes for tooltip block
This commit related on tasks JC-1938, JC-1939
=> JC-1938 Incorrect text wrapping in tooltip on mouse over the ukrainian flag

jcommune-view/jcommune-web-view/src/main/webapp/resources/css/app/application.css
Problem was in .btn-group .btn:last-child(bootstrap.css) selector.
It doesn't work when tooltip created,
because button isn't last child of .btn-group element after tooltip
creation. I overwrited this style in application.css with
:last-of-type pseudoclass
=> JC-2130 Disappearing corners of 'delete', 'quote' buttons fixed

jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/controller/PostController.java, jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/PostControllerTest.java
There was changed error handling behavior. Now, instead of redirecting
to view it redirects to an error handling controller method. Thus, when
user refreshes page only GET request is repeated. In consequence, it
allows saving drafts and prevents unexpected text body errors.
=> JC-1739 Fix of issue with repeated post request after refresh

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/postDraft.js
Fix for issue with appearing draft in answer form after submitting with hot-keys 'ctr+enter' in Firefox
=> JC-1739 Posted draft in Q/A topic doesn't remove

jcommune-model/src/main/java/org/jtalks/jcommune/model/entity/JCUser.java, jcommune-model/src/main/java/org/jtalks/jcommune/model/entity/ObjectsFactory.java, jcommune-model/src/test/java/org/jtalks/jcommune/model/entity/JCUserTest.java
We have to customize serialization of the entity JCUser because of we used to loose 'id' and 'uuid' data from org.jtalks.common.model.entity.Entity class when saved other User details in session-storage-file.
The fix is similar to issue of PoulpeUser serialization (http://jira.jtalks.org/browse/POULPE-528)
Created:
- methods writeObject(), readObject() and serialVersionUID field.
- test method for checking is most fields of User entity serialized
- test method to assert the field `List<Group> groups` can't be serialized with rest of the JCUser fields.
Implemented additional ObjectFactory method to reduce size of code in test method.
=> Poulpe-528 Issue with 'User #0 not found' error

jcommune-plugins/kaptcha-plugin/src/main/java/org/jtalks/jcommune/plugin/kaptcha/KaptchaPluginService.java, jcommune-plugins/kaptcha-plugin/src/main/resources/org/jtalks/jcommune/plugin/kaptcha/template/captcha.vm
Fix for [http://jira.jtalks.org/browse/JC-2094] issue. Query t="date" added because Firefox ignores cache control headers if DOM changed by JavaScript and no way to prevent image caching.
=> JC-2094 Refresh captcha in Firefox.

jcommune-plugins/kaptcha-plugin/src/main/resources/org/jtalks/jcommune/plugin/kaptcha/template/captcha.vm, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/registration.js
- refresh img wrapped with < button >, since can't focus img.
- Added #refreshCaptchaBtn id to tabNavigation list.
- changed refreshCaptcha function because click event caused POST request to nonexistent resource.
=> JC-2086 Refresh captcha via TAB:

jcommune-plugins/kaptcha-plugin/src/main/resources/org/jtalks/jcommune/plugin/kaptcha/template/captcha.vm, jcommune-plugins/kaptcha-plugin/src/test/java/org/jtalks/jcommune/plugin/kaptcha/KaptchaPluginServiceTest.java, jcommune-view/jcommune-web-view/src/main/webapp/resources/css/app/application.css, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/registration.js
- refresh img wrapped with < div >, since img tag can't be in focus .
- added style 'btn-captcha-refresh' which overrides bootstrap button style.
- added  class '.btn-captcha-refresh'  to tabNavigation list.
- added separated keyboard handler to update captcha through keyboard.
- restored button style and sign up form behaviour.
=> JC-2086 Refresh captcha via TAB [REWORKED]:

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/signin.js
- fixed tabNavigation property of the Sign-In dialogue.
P/S: note at the bottom of this issue: "cursor is not focused on “Save” button when moving via Tab key" is not confirmed, because I have the focus on Save button via Tab (in browsers Opera 12.17, Crome 45.0.2454.101 m).
=> JC-2126 On Sign In popup window cursor is not focused on link

jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/dto/UserSecurityDto.java
- added a message attribute of the annotation Size (the newUserPassword
field of the UserSecurityDto class)
P/S: reopened the pull request because accidentally deleted the branch.
=> JC-1998 Wrong error message below the new password field

jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/topic/searchResult.jsp
- replaced classes responsible for a dimension elements "div".
=> JC-2018 text of "Recent activity" and "Search results" have two rows

jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/login.jsp, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/registration.jsp, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/restorePassword.jsp, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/global.js
- added a code that selects the input field with the attribute
"autofocus" of the form when page is loaded. Made to support
the set focus on the element with attribute "autofocus" in browsers
that do not support HTML5.
- added the attribute "autofocus" to the field "user name" on the pages:
registration, login.
- added the attribute "autofocus" to the field "user email" on the password
recovery page.
=> JC-2268 Focus on sign in/sign up pages should be on first input field

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/dialog.js, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/signin.js
- fixed suggestion behavior in firefox.
P/S 1: found duplicated issue - JC-2213.
P/S 2: in my opinion, the below code in signin.js is redundant because the element '#restorePassSuccess' is missing (or is it groundwork for the future?):
var success = $('#restorePassSuccess');
if (success.length > 0) {
var bodyContent = '\
<div id="restore-passwd" class="control-group"> \
<h4>' + success.val() + '</h4> \
</div>';
var footerContent = '<button id="restore-ok-button" class="btn btn-primary" name="confirm"> \
' + $labelOk + '</button>';
var goToLoginPage = function (e) {
if (e) {
e.preventDefault();
}
window.location.href = $('.brand').attr('href') + 'login';
};
jDialog.createDialog({
dialogId: 'restore-password-modal-dialog',
closeDialog: goToLoginPage,
bodyContent: bodyContent,
footerContent: …
=> JC-2134 The user's selection does not work by Enter in Firefox

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/contextMenu.js
- deleted "focusout" event handler of the fields "recipient", which is triggered before "select" events of the autocomplete widget. Instead, I added an event handler "change" to the autocomplete widget, that is triggered when the field is blurred, if the value has changed.
=> JC-2281 Error "User not found" error when the recipient is selected from list by the mouse

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/postDraft.js, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/topicDraft.js
Bug reason: function "wasChanged" compares the value of the field with the stored draft values rather than actual, so validation does not occur when deleting extra symbol
Solution: listen "input" event instead "onKeyUp" event, because "input" event triggered only if field changed
=> JC-2274 Fixed bug: validation message about field length in drafts after changing focus doesn't disappear after deleting extra symbol

jcommune-plugin-api/src/main/resources/org/jtalks/jcommune/jcommune-plugin-api/web/templates/bbeditor.vm, jcommune-service/src/main/resources/kefirbb-strip-config.xml, jcommune-service/src/main/resources/kefirbb.xml, jcommune-service/src/test/java/org/jtalks/jcommune/service/nontransactional/BBCodeServiceTest.java, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/tags/bbeditor.tag, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/lib/wysiwyg-bbcode/editor.js
There is no more "Add syntax higlight" button described in the topic of
this task in Jira, this button's name is "Code".
Got rid of drop-down menu because it does not matter what programming
language we choose in the drop-down list of button "Code". The syntax will
be displayed correct depending on what language it is written.
Pressing button "Code" you will have this construction: [code=]Insert your
text here[/code]
Still old version of constraction e.g [code=java]Insert your text
here[/code] is working correctly too.
modified files:
jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/tags/bbeditor.tag
jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/lib/wysiwyg-bbcode/editor.js
=> JC-2194 Got rid of drop-down menu of "Code" button

jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/tags/bbeditor.tag, jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/lib/wysiwyg-bbcode/editor.js
Some browsers could have selectionStart and selectionEnd that is not equal
to 0 for empty textarea.
E.g. opera 12 has 15. So it's better to assign 0 in order not to have
problems in the future.
I also incidentally found and corrected an inaccuracy in the file
bbeditor.tag.
It was
`title='<spring:message code='label.answer.highlight'/>'>`
changed to
`title="<spring:message code='label.answer.highlight'/>">`
=> JC-2170 Wrong tags for sintax highlight in Opera12

jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/security-context.xml
In file `security-context.xml` rule for `/user/*/groups/*` mask configured only for `GET `methods. But add and delete requests type `POST `and `DELETE`. Now rule shared for all methods.
=> JC-2292 Group add and delete security fix

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/forumAdministration.js
I moved call of function 'createAdministrationDialog' into a new function 'cancel' with termination operation 'return false'. This was a cause of the error 500.
=> JC-2327 Remove Logo/Fav Icon button bug fix

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/forumAdministration.js
I fixed the problem with checkbox email notifications.
The cause of this problem is was a comparing admin value 'emailNotification' as a boolean(=== true),
but need to compare this as a String(=== 'true') because the return value type of 'emailNotification' is a String.
Actual result if email notifications is disabled - checkbox is 'unchecked'
=> JC-2309 Notifications bug fix

jcommune-view/jcommune-web-view/pom.xml
The web resource optimizer (wro4j-maven-plugin) not correctly rewrites
URLs of resources in css-files on Windows platforms. As a result,
resources become unavailable and user, for example, does not sees
the icons on the toolbar buttons. The behavior is due to incorrect
`contextFolder` variable definition inside plugin
(bug report: https://github.com/wro4j/wro4j/issues/1021).
To solve described problem made the following changes:
- in pom.xml added additional path for `contextFolder` parameter specified
in Windows style (with back slashes).
- changed version of wro4j-maven-plugin from 1.7.5 to 1.7.6, because
old versions of the plugin have additional bug associated with
described problem.
=> Fix working of the web resource optimizer on Windows platforms

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/forumAdministration.js
Email notifications checkbox doesn't show saved 'Unchecked' value - Fixed
I was change comparing of variable 'emailNotification', now it's always will compare as a String
=> JC-2309 Email notifications fix bug

jcommune-view/jcommune-web-view/src/main/webapp/resources/javascript/app/forumAdministration.js
Ids of some html components were mistaken within 'tabNavigation' property.
=> JC-2309 Fixed wrong focus navigation through administration popup

jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/editProfile.jsp
Included JSTL's c:out tag for
${editedUser.username} expression
in editProfile.jsp. Because this tag
escapes HTML characters for
avoid cross-site scripting.
=> JC-2289 XSS vulnerability at profile page bug fix

jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/ReadPostsControllerTest.java
RetryPolicy changed
According to javadoc for tests purpose recommended to use NeverRetryPolicy
changes made in ReadPostsControllerTest.java
=> JC-2005 Fixed multiple clicking on 'Mark all as read'

jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V65__Add_admin_user.sql, jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V73__Convert_Database_To_UTF8MB4_Encoding.sql, jcommune-model/src/main/resources/org/jtalks/jcommune/model/sample-forum.sql, jcommune-model/src/test/java/org/jtalks/jcommune/model/dao/hibernate/GroupHibernateDaoTest.java, jcommune-view/jcommune-web-view/src/main/resources/org/jtalks/jcommune/model/datasource.properties, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/groupAdministration.jsp
Previously jcommune used 'UTF-8' character set. But due to [JC-2001] Entering smile from mobile keypad
leads to Error 500, we wanted to change database character set to 'utf8mb4'. Also due to [JC-2321]
Usergroups list order is case-sensitive, collation must be 'utf8mb4_unicode_ci'.
- Now default database character set is 'utf8mb4' and collation 'utf8mb4_unicode_ci'
- All tables in the database converted to character set 'utf8mb4' and collation 'utf8mb4_unicode_ci', except jcommune_schema_version, because it is blocked by flyway.
- Removed characterEncoding parameter from jdbc connection url because since version 5.1.13 Connector/J did not support utf8mb4 for servers 5.5.2 and newer. Now it takes from the server settings. (https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-13.ht …
=> JC-2291.MigrationToUtf8mb4

jcommune-model/src/main/resources/org/jtalks/jcommune/model/entity/Branch.hbm.xml, jcommune-model/src/main/resources/org/jtalks/jcommune/model/entity/Topic.hbm.xml, jcommune-model/src/main/resources/org/jtalks/jcommune/model/entity/applicationContext-dao.xml, jcommune-view/jcommune-web-view/src/test/resources/org/jtalks/jcommune/web/view/test-configuration.xml, pom.xml
Interim update of the Flyway for subsequent updates to version 4.0.
Optimized Flyway beans in application Context.
Change version of HSQLDB to 2.3.3 for test usage.
Used explicit type conversion in Topic and Branch entities because
auto casting behaviour has become more strict in HSQLDB.
=> Update version of Flyway to 2.3.1

jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V65__Add_admin_user.sql, jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V6__Acl_Sid_encoding_fix.sql, jcommune-model/src/main/resources/org/jtalks/jcommune/migrations/V6__Acl_encoding_fix.sql
- vars with different type of colllations can not be compared by '='
that's why need to set connection collation the same as database collation
in spite of server configuration.
=> fixed illegal mix of collations

jcommune-performance-tests/src/test/scala/Engine.scala, jcommune-performance-tests/src/test/scala/IDEPathHelper.scala, jcommune-performance-tests/src/test/scala/Recorder.scala, jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenForumMainPage.scala, pom.xml
- include *.scala and exclude [logback.xml, *.conf, *.tag, *.index, *.jpeg, *.md, *.pcx, *.pdf] file types in maven-license-plugin to check licence header.
- remove spaces from licence headers.
=> Fix licence headers.

jcommune-performance-tests/README.md, jcommune-performance-tests/pom.xml, jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/model/User.scala, jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/Login.scala, jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/tests/OpenRecentActivityPage.scala, jcommune-performance-tests/src/test/scala/org/jtalks/jcommune/performance/utils/ScnBuilder.scala
- removed configuration from pom.xml, now there is only one parameter -
performance.url that should contain full url path to application server
and should be passed as an argument to Maven.
- removed credentials.csv, now credential storage is a Map<paramName,
param> in org.jtalks.jcommune.performance.model.User
- removed redundant string concatenations
- changed readme.md
TODO: add comments
=> Modify gatling scenarios.

jcommune-performance-tests/README.md, jcommune-performance-tests/pom.xml, pom.xml
We didn't include Performance System Tests in the reactor because we
didn't want to run them when unit/component tests are run. But the
downside was that you can't run the performance tests without
previously installing the parent POM.
To have both problems solved - the module is added to the list of
modules, but `mvn test` won't invoke the actual tests until a special
flag is passed. Ultimately to run just the performance tests:
`mvn -pl jcommune-performance-tests -Dperformance-test.skip=false`
=> Include performance tests module into reactor

jcommune-model/src/main/java/org/jtalks/jcommune/model/entity/Topic.java, jcommune-model/src/test/java/org/jtalks/jcommune/model/entity/TopicTest.java, jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/controller/ReadPostsController.java, jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/controller/TopicController.java, jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/ReadPostsControllerTest.java, jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/TopicControllerTest.java, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/jsp/topic/postList.jsp, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/spring-dispatcher-servlet.xml, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/ReadPostsControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/TopicControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Topics.groovy, jcommune-view/jcommune-web-view/src/test/resources/org/jtalks/jcommune/web/view/test-configuration.xml
* removed "mark as read" functionality from the topic controller
* created separate request for marking topics as read
* added url invocation to the topic for authorized users
* enabled request caching for this url
=> JC-2306 - mark topic as read by separate request

jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/AdministrationControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/model/GroupDto.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/service/GroupsService.java, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Groups.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Users.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/assertions/Assert.groovy
- added Groovy tests for editing group method in AdministrationController
//Next steps
- realize method isEditable() //returns false if group.name is equal to one of the next group names: {"Administrators", "Registered Users", "Banned Users"}, otherwise  returns true.
- add constructor(long id, String name, String description, int count) to populate DTO right from HQL query.
=> JC-2367 Edit user groups (Groovy tests)

jcommune-model/pom.xml, jcommune-model/src/main/resources/org/jtalks/jcommune/model/entity/ehcache.xml, jcommune-service/pom.xml, jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/controller/AdministrationControllerTest.java, jcommune-view/jcommune-web-controller/src/test/java/org/jtalks/jcommune/web/interceptors/LocalInterceptorTest.java, pom.xml
Since we do not need the functionality of Poulpe (except authentication), we
also do not need distributed cache anymore.
=> Get rid of JGroups

jcommune-service/src/main/java/org/jtalks/jcommune/service/transactional/TransactionalUserService.java
We are faced with the strange behavior of the application, activated users after some time become not activated. Therefore, to get rid of new exceptions which thrown while deleting non-activated users it is necessary to suspend this action.
=> Stop deleting non-activated users

jcommune-service/src/main/java/org/jtalks/jcommune/service/security/SecurityService.java, jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/listeners/HttpRequestListener.java, jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/listeners/SessionSetupListener.java, jcommune-view/jcommune-web-controller/src/main/java/org/jtalks/jcommune/web/util/AppContextUtils.java, jcommune-view/jcommune-web-view/src/main/webapp/WEB-INF/web.xml
Tomcat can't remove JCUser objects from thread-local variables after application stop, so let's remove them after each Http request.
=> clean up thread-locals

jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/AdministrationControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/AuthenticatorTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/CreateBranchTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/LocationServiceTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/ReadPostsControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/SignInTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/SignUpTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/SpamProtectionRestApiTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/TopicControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/TopicSearchControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/UserControllerTest.groovy, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/service/GroupsService.java, jcommune-view/jcommune-web-view/src/test/java/org/jtalks/jcommune/test/utils/Groups.groovy
get rid of direct access to dao for 'create new group' operation in integration tests level.
=> get rid of direct access to dao for 'create new group' operation in integration tests level.
